### ISSUE TITLE
translate FAQs Waves for Brazilian Portuguese

### ISSUE THREAD

**Issue by EvertonMelo** [wavesplatform/waves-documentation#124]
Hi,

what would be the best way to translate FAQ or getting-started ?
Waves Plataform have a biggest Community on Brazil, but has little documentation in pt-br.

What would be the best way to start the translation?

**Comment by EvertonMelo** [comment]
@gingerabsurdity @Nazeim 

you can help me?

**Comment by Nazeim** [comment]
@EvertonMelo 
Yes I can help you,
I will try to add multi-language feature to our docs

**Comment by EvertonMelo** [comment]
@Nazeim 

What's the best way to do this?

structure:
 **"i18n/pt-BR/"**

**Comment by Nazeim** [comment]
Hi,
I have added a pt-br folder to our docs, you can write the translation there and you can start with the overview section,
Please check the structure of English folder(en) in order to follow the same structure.
Here you can make a pull request:
https://github.com/wavesplatform/waves-documentation/tree/MultiLangDocs

**Comment by EvertonMelo** [comment]
@Nazeim 
Thank you, 

I start a translate in my Github, after PR for here.

**Comment by hanelore** [comment]
Do you need help @EvertonMelo ?

**Comment by Nazeim** [comment]
@EvertonMelo @hanelore 
Great :)
waiting for your pull request

**Comment by wesleysd1989** [comment]
I started the translation, I already sent a 'pull request'
